version: 2.1

jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-14.27
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - cci-haskell-v1-{{ checksum "blog.cabal" }}-{{ checksum "stack.yaml" }}
            - cci-haskell-v1-{{ checksum "blog.cabal" }}
            - cci-haskell-v1-
      - run:
          name: Resolve Dependencies
          command: stack --no-terminal setup
      - run:
          name: Build Dependencies
          command: stack --no-terminal build -j1 --fast --dependencies-only
      - save_cache:
          name: Cache Dependencies
          key: cci-haskell-v1-{{ checksum "blog.cabal" }}-{{ checksum "stack.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
      - run:
          name: Build
          command: stack --no-terminal build --copy-bins
      - persist_to_workspace:
          root: '/root/.local/bin'
          paths: "site"

  generate:
    docker:
      - image: blang/latex:ubuntu
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/
      - run:
          name: Generate Site
          command: /tmp/site build
      - persist_to_workspace:
          root: '/root/project/'
          paths: "_site/"

  publish:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout # Get CircleCI to populate SSH keys so that we trust GitHub
      - attach_workspace:
          at: /tmp/
      - run:
          name: Publish Site
          working_directory: /tmp/_site
          command: |
            git init
            git config user.name 'CircleCI'
            git config user.email 'job@circleci.com'
            git add .
            git commit -m "Update (`date '+%F %T %Z'`) [ci_skip]"
            git remote add origin "git@github.com:thjread/thjread.github.io.git"
            git push --force origin master

workflows:
  version: 2

  build_and_publish:
    jobs:
      - build
      - generate:
          requires:
            - build
      - publish:
          requires:
            - generate
          filters:
            branches:
              only: master
